name: 'Checkov'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          skip_check: CKV_AWS_1 # optional: skip a specific check_id
          quiet: false # optional: display only failed checks
          
