name: "Terraform Module Update"
defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - develop
      - master

jobs:
  module:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2-beta

      - name: Create AWS Profile
        run: make test
