on: [push]

jobs:
  TFL:
    runs-on: ubuntu-latest
    name: TFL
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: Hello world action step
      id: Terraform
      uses: ./github/workflows/action.yml
