
name: 'Test'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v1

      - name: Run image
        run: docker run -it -d --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint  > text.txt
     
      - name: echo text
        uses: pCYSl5EDgo/cat@master
        id: hello
        with:
        path: text.txt

      - run: echo $TEXT
        env:
        TEXT: ${{ steps.hello.outputs.text }}
