name: 'Test2'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: Run image
        run: docker run -it -d --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint 
     
      - name: run docker logs
        run: docker logs TFLint > test.txt
      
      - name: echo test
        uses: pCYSl5EDgo/cat@master
        id: hello
        with:
          path: test.txt

      - run: echo $TEXT
        env:
          TEXT: ${{ steps.hello.outputs.text }}
    
      - name: Get text
        id: vars
        run: echo ::set-output name=test::$(cat test.txt)
        
      - name: Test output
        run: if "docker logs TFLint" foo; then echo error|| exit 2; else echo All ok; fi
