name: 'ReviewDog'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform init'
        run: terraform init
            
      - name: 'Setup reviewdog'
        run: |
         mkdir -p $HOME/bin && curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b $HOME/bin
         echo ::add-path::$HOME/bin
         
      - name: 'Run ReviewDog'
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker run --rm --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint --format=checkstyle | reviewdog -f=checkstyle -name="tflint" -reporter=github-check -level=warning -fail-on-error -filter-mode=nofilter
     
      
      
         
