name: 'Terraform Plan'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt -check
       
      - name: Check linting of Terraform files
        uses: devops-infra/action-tflint@master
        with:
        tflint_params: "--module --deep"
        dir_filter: modules
