name: Check TFLint
on:
  push:
jobs:
  format-hcl:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Check linting of Terraform files
      uses: devops-infra/action-tflint@master
    - name: run docker logs
      run: docker logs devopsinfraactiontflintlatest_f881e1
