name: 'Check TFLint'
on: [push, pull_request]
defaults:
      run:
        shell: bash

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Init'
        run: terraform init || docker run -it -d --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint > test.txt

      - name: Check test
        run: |
         "[[ -f test.txt && ! -s test.txt ]]" && echo "filename exists and is empty"|| echo "fuck"




      - name: 'Terraform Format'
        run: terraform fmt -check

      - name: Run image
        run: docker run -it -d --name TFLint -v $GITHUB_WORKSPACE:/data -t wata727/tflint
     
      - name: run docker logs
        run: docker logs TFLint
      
         
